# Generated by Django 2.2.4 on 2019-09-03 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0007_auto_20190829_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
